### ISSUE TITLE
What is the minimum VRAM of the software?

### ISSUE THREAD

**Issue by ninjasaid2k** [B34STW4RS/AD-Evo-Tuner#5]

**Comment by B34STW4RS** [comment]
answered in updated readme, probably a 3090/4090 for now, might be able to squeak by with less depending on size of dataset. submit issues with ram problems and I'll see if I can get it sorted.

With a small set I've seen it hover around 12 ish, with a larger set around 20.

**Comment by neph1** [comment]
Since I imagine this is a common question ( I know I wondered as well), here are my first findings.
I have a 3060 with 12GB VRAM.
I can run 256x256 training, 16 frames, "to_q" module. @ 8.9GB, 1.46s/it (1000 iterations in 25 minutes)
Going up to 512x512 I can train 8 frames (maybe a few more).
"train_whole_module" is out of the question.
